name: Docker Deployment CI/CD

on:
  push:
    branches:
      - develop

jobs:
  ssh-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: nattech.fib.upc.edu
          username: alumne
          password: ${{ secrets.SSH_PASSWORD }} # Aquí debes haber guardado previamente tu contraseña en los secretos de GitHub
          port: 22047
          script: |
            echo "Conectado al servidor"
            
            
            
            
            
            
